[2023-11-08 17:59:19] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn bc84b5d09f1aa914 127.0.0.1:63144 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:59:19] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn bc84b5d09f1aa914 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2023-11-08 17:59:25] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-11-08 17:59:25] [warning] synchronization.go:205 dpchain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (30f2b28aa99eacc5db2aaeddb3668bc44e0ff2ef4a14eddf56ee67c9ccefcdb46450e03e6d41adbc01ad370a6faebe78580bff424678fa5881210f9123cadecf), err:EOF

[2023-11-08 17:59:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-11-08 17:59:25] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20133: connect: connection refused
[2023-11-08 17:59:25] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

